config/routes.rb
JobBoard::Application.routes.draw do
  resources :companies, :only => [:new, :create]

  namespace :company do
    resources :job_positions
  end

  resources :job_positions, :only => [:index, :show]

  resource :session, :only => [:new, :create, :destroy]

  root :to => 'job_positions#index'

end

app/models/company.rb
require "digest"

class Company < ActiveRecord::Base
  validates_presence_of :name, :email, :password

  before_save :encrypt_password

  validates_uniqueness_of :email

  attr_accessor :password
  attr_accessible :password, :name, :email

  has_many :job_positions

  def valid_password?(password)
    self.encrypted_password == Digest::SHA2.hexdigest(password + password_salt + "secot")
  end

  def encrypt_password
    generate_salt
    self.encrypted_password = Digest::SHA2.hexdigest(password + password_salt + "secot")
  end

  def generate_salt
    self.password_salt = random_string
  end

  def random_string
    ('a'..'z').to_a.shuffle.join
  end
end

app/models/job_position.rb
class JobPosition < ActiveRecord::Base
  validates_presence_of :position, :description

  validates_length_of :description, :maximum => 500

  belongs_to :company

  attr_accessible :description, :position, :start_date
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery

  helper_method :current_company


  protected

  def redirect_if_logged
    if session[:company_id]
      flash[:error] = "You should not be logged in to access this area"
      redirect_to company_job_positions_path
    end
  end

  def redirect_if_not_logged
    unless session[:company_id]
      flash[:error] = "You should be logged in to access this area"
      redirect_to new_session_path
    end
  end

  def current_company
    if session[:company_id]
      @company ||= Company.find(session[:company_id])
    end
  end
end

app/controllers/companies_controller.rb
class CompaniesController < ApplicationController
  before_filter :redirect_if_logged

  def new
    @company = Company.new
  end

  def create
    @company = Company.new(params[:company])

    if @company.save
      #login do usuário
      session[:company_id] = @company.id

      #redirecionar
      redirect_to "/"
    else
      render 'new'
    end
  end
end

app/controllers/company/job_positions_controller.rb
class JobPositionsForCompaniesController < ApplicationController
  before_filter :redirect_if_not_logged

  def index
    @job_positions = current_company.job_positions
  end

  def new
    @job_position = current_company.job_positions.new
  end

  def create
    @job_position = current_company.job_positions.new(params[:job_position])

    if @job_position.save
      flash[:notice] = "You have created a job position successfully"

      redirect_to job_positions_path
    else
      render 'new'
    end
  end

  def edit
    @job_position = current_company.job_positions.find(params[:id])
  end

  def update
    @job_position = current_company.job_positions.find(params[:id])

    if @job_position.update_attributes(params[:job_position])
      flash[:notice] = "You have updated successfully"

      redirect_to job_positions_path
    else
      render 'edit'
    end
  end

  def destroy
    @job_position = current_company.job_positions.find(params[:id])

    @job_position.destroy

    flash[:notice] = "You have deleted successfully"

    redirect_to job_positions_path
  end
end

app/controllers/job_positions_controller.rb
class JobPositionsController < ApplicationController
  def index
    @job_positions = JobPosition.all
  end

  def show
    @job_position = JobPosition.find(params[:id])
  end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  before_filter :redirect_if_logged, :except => :destroy
  before_filter :redirect_if_not_logged, :only => :destroy

  def new
  end

  def create
    @company = Company.where(:email => params[:company][:email]).first
    if @company && @company.valid_password?(params[:company][:password])
      session[:company_id] = @company.id
      redirect_to company_job_positions_path
    else
      flash[:error] = "Invalid user or password"
      redirect_to new_session_path
    end
  end

  def destroy
    session[:company_id] = nil
    flash[:notice] = "You have logged out"
    redirect_to new_session_path
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/companies_helper.rb
module CompaniesHelper
end

app/views/companies/new.html.erb
<%= form_for @company do |f| %>
  <%= f.error_messages %>
  <p>
    <%= f.label :name, "Nome" %>
    <%= f.text_field :name %>
  </p>

  <p>
    <%= f.label :email, "Email" %>
    <%= f.text_field :email %>
  </p>

  <p>
    <%= f.label :password, "Senha" %>
    <%= f.password_field :password %>
  </p>

  <p>
    <%= f.button "Sign up" %>
  </p>
<% end %>

app/views/company/job_positions/edit.html.erb
<h1>Edit job position</h1>

<%= form_for @job_position do |f| %>
  <%= f.error_messages %>
  <p>
    <%= f.label :position, "Cargo" %>
    <%= f.text_field :position %>
  </p>

  <p>
    <%= f.label :description, "Descrição" %>
    <%= f.text_area :description %>
  </p>

  <p>
    <%= f.label :start_date, "Data de início" %>
    <%= f.date_select :start_date %>
  </p>

  <p>
    <%= f.button "Update job position" %>
  </p>
<% end %>

app/views/company/job_positions/index.html.erb
<% @job_positions.each do |job_position| %>
  <p>
    Cargo: <%= job_position.position %>
  </p>

  <p>
    Descrição: <%= job_position.description %>
  </p>

  <p>
    Data de início: <%= job_position.start_date %>
  </p>

  <p>
    <%= link_to "Edit this job position", edit_company_job_position_path(job_position.id)%>
  </p>

  <p>
    <%= link_to "Delete this job position", company_job_position_path(job_position.id), :method => :delete %>
  </p>
<% end %>

<%= link_to "New job position", new_company_job_position_path %>

app/views/company/job_positions/new.html.erb
<h1>New job position</h1>

<%= form_for @job_position do |f| %>
  <%= f.error_messages %>
  <p>
    <%= f.label :position, "Cargo" %>
    <%= f.text_field :position %>
  </p>

  <p>
    <%= f.label :description, "Descrição" %>
    <%= f.text_area :description %>
  </p>

  <p>
    <%= f.label :start_date, "Data de início" %>
    <%= f.date_select :start_date %>
  </p>

  <p>
    <%= f.button "Create job position" %>
  </p>
<% end %>

app/views/job_positions/index.html.erb
<ul>
  <% @job_positions.each do |job_position| %>
    <li>
      <%= link_to job_position_path(job_position.id) do %>
        <%= job_position.position %> at <%= job_position.company.name %>
      <% end%>
    </li>
  <% end %>
</ul>

app/views/job_positions/show.html.erb
<p>
  <%= @job_position.position %>
</p>

<p>
  <%= @job_position.description %>
</p>

<p>
  <%= @job_position.start_date %>
</p>

<p>
  E-mail para envio do currículo:
  <%= @job_position.company.email %>
</p>

<p>
  <%= link_to "Voltar para vagas", job_positions_path %>
</p>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>JobBoard</title>
  <%= stylesheet_link_tag    "application", :media => "all" %>
  <%= javascript_include_tag "application" %>
  <%= csrf_meta_tags %>
</head>
<body>

<% if current_company %>
  <%= "You are logged in as #{current_company.email}"%>
  -
  <%= link_to "Log out", session_path, :method => :delete %>
<% else %>
  <%= link_to "Log in", new_session_path %>
<% end %>

<%= flash[:error] %>
<%= flash[:notice] %>

<%= yield %>

</body>
</html>